import { test } from 'node:test';
import * as assert from 'node:assert/strict';
import { resolveFromYarnLock } from '../src/core/lockfiles';

const classicLock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/core@^7.24.0":
  version "7.24.7"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.7.tgz"

lodash@^4.17.0, lodash@^4.17.20:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
`;

const berryLock = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10

"react@npm:^18.2.0":
  version: 18.3.1
  resolution: "react@npm:18.3.1"

"@scope/pkg@npm:~2.0.0":
  version: 2.0.4
  resolution: "@scope/pkg@npm:2.0.4"
`;

test('yarn classic: matches the declared range descriptor', () => {
  assert.equal(resolveFromYarnLock(classicLock, 'lodash', '^4.17.0'), '4.17.21');
  assert.equal(resolveFromYarnLock(classicLock, '@babel/core', '^7.24.0'), '7.24.7');
});

test('yarn classic: falls back to any entry for the package when the range differs', () => {
  assert.equal(resolveFromYarnLock(classicLock, 'lodash', '^4.16.0'), '4.17.21');
});

test('yarn berry: matches npm: protocol descriptors', () => {
  assert.equal(resolveFromYarnLock(berryLock, 'react', '^18.2.0'), '18.3.1');
  assert.equal(resolveFromYarnLock(berryLock, '@scope/pkg', '~2.0.0'), '2.0.4');
});

test('yarn: does not confuse package names sharing a prefix or __metadata', () => {
  assert.equal(resolveFromYarnLock(berryLock, '__metadata', '*'), undefined);
  assert.equal(resolveFromYarnLock(classicLock, 'lo', '^1.0.0'), undefined);
});
